name: Test_Zone_Bon_Plan
on: [push] # S'active à chaque fois que tu enregistres un truc sur GitHub

jobs:
  discord-message:
    runs-on: ubuntu-latest
    steps:
      - name: Envoi test
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "🚀 Test réussi ! Le site Zone Bon Plan vient d'être mis à jour."}' \
          ${{ secrets.DISCORD_WEBHOOK }}
